Timerime\TimelineBundle\Entity\Timeline:
  type: entity
  table: timeline
  repositoryClass: Timerime\TimelineBundle\Entity\TimelineRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 45
      fixed: false
      nullable: true
    content:
      type: string
      length: 45
      fixed: false
      nullable: true  
  oneToMany:
    timeline_items:
      targetEntity: TimelineItem
      mappedBy: timeline
    timeline_periods:
      targetEntity: TimelinePeriod
      mappedBy: timeline
  manyToOne:
    author:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: timeline
      joinColumns:
        author_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
