Timerime\TimelineBundle\Entity\Myentity:
  type: entity
  table: myentity
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 50
      fixed: false
      nullable: false
    description:
      type: string
      length: 255
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
