Timerime\TimelineBundle\Entity\Timeline:
  type: entity
  table: timeline
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 45
      fixed: false
      nullable: true
    content:
      type: string
      length: 45
      fixed: false
      nullable: true
  oneToOne:
    author:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        author_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
