Timerime\TimelineBundle\Entity\User:
  type: entity
  table: user
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    username:
      type: string
      length: 45
      fixed: false
      nullable: true
    email:
      type: string
      length: 45
      fixed: false
      nullable: true
    password:
      type: string
      length: 45
      fixed: false
      nullable: true
    type:
      type: string
      length: 50
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
