Timerime\TimelineBundle\Entity\TimelinePeriod:
  type: entity
  table: timeline_period
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
    timelineId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: timeline_id
    authorId:
      type: string
      length: 45
      fixed: false
      nullable: true
      column: author_id
    startdate:
      type: string
      length: 45
      fixed: false
      nullable: true
    enddate:
      type: string
      length: 45
      fixed: false
      nullable: true
  manyToOne:
    timeline:
      targetEntity: Timeline
      cascade: {  }
      mappedBy: null
      inversedBy: timeline_period
      joinColumns:
        timeline_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
