<?php

namespace Timerime\TimelineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimelineRepository extends EntityRepository
{
	public function getTimelines()
	{
		return $this->findAll();
	}
}